server:
  address: 127.0.0.1
  port: 8080

spring:
  profiles:
    default: dev
  application:
    name: greenly-api
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
